name: Better Dependabot

on:
  schedule:
    - cron: "0 0 * * *" # Supposedly at the end of every day.
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Update cheatGUI dependencies
      run: |
        cd ./cheatGUI/
        npm update
    - name: Update typings dependencies
      run: |
        cd ./typings/
        npm update
    - name: Update PHEx dependencies
      run: |
        cd ./PHEx/
        npm update        
    - name: Commit with git
      run: |
        git pull
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit --allow-empty -s -m "AutoBuild cheatGUI"
    - name: Push changes to GitHub
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}        
